---
- name: Installing web server
  hosts: all
  become: true
  tasks:
  - name: Installing httpd
    yum:
      name: httpd
      state: present
  - name: Starting service httpd
    service:
      name: httpd
      state: started
