---
- name: Setup tomcat
  hosts: all
  become: true
  tasks:
  - name: Install java in RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install java in Debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: Download Tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
      dest: /opt

  - name: Extract Tomcat
    unarchive:
      src: /opt/apache-tomcat-9.0.54.tar.gz
      dest: /opt
      remote_src: true

  - name: Execute Permission
    file:
      path: /opt/apache-tomcat-9.0.54/bin/startup.sh
      mode: 0777

  - name: Start Tomcat Service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-9.0.54/bin/

